language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
 - perlbrew install-cpanm -f
install:
  - cpanm --quiet --notest WWW::Shorten JSON::PP Test::Pod Test::Pod::Coverage Test::Kwalitee Test::Pod::No404s
script: "export EXTENDED_TESTING=1 && export RELEASE_TESTING=1 && perl Makefile.PL && make disttest"
